{% set name = "aiida-abinit" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiida-abinit-{{ version }}.tar.gz
  sha256: 1af665b6bc5288ee9d85f2a2b1c91dd4a13aaafc1bf057a661a4b35e3d5725e2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - reentry
  run:
    - aiida-core >=1.1.0,<2.0.0
    - aiida-pseudo >=0.5.0
    - python >=3.6
    - six
    - voluptuous

test:
  imports:
    - aiida_abinit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sponce24/aiida-abinit
  summary: The AiiDA plugin for ABINIT.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisjsewell
